# Generated by Django 2.2.3 on 2019-07-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroDeUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=20)),
                ('data_nascimento', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=14)),
                ('celular', models.CharField(max_length=14)),
                ('genero', models.CharField(choices=[('fem', 'Feminino'), ('tra', 'Transsexual'), ('otr', 'Outros')], max_length=3)),
                ('senha', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DepoimentosUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_depoimento', models.CharField(max_length=40)),
                ('depoimento', models.TextField(default='')),
                ('foto_depoimento', models.ImageField(upload_to='')),
                ('nome', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='app.CadastroDeUsuario')),
            ],
        ),
    ]
