# Generated by Django 2.2.3 on 2019-07-12 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_entrar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrar',
        ),
    ]
