# Generated by Django 2.2.3 on 2019-07-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_entrar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depoimentosusuario',
            old_name='foto_depoimento',
            new_name='foto',
        ),
        migrations.AlterField(
            model_name='cadastrodeusuario',
            name='genero',
            field=models.CharField(choices=[('---', '----------------------'), ('fem', 'Feminino'), ('otr', 'Outros')], default='', max_length=3),
        ),
    ]
