# Generated by Django 2.2.3 on 2019-07-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190712_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depoimentosusuario',
            old_name='foto',
            new_name='imagem',
        ),
    ]
