# Generated by Django 2.2.3 on 2019-07-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_depoimentosusuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrodeusuario',
            name='genero',
            field=models.CharField(choices=[('', ''), ('fem', 'Feminino'), ('otr', 'Outros')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='depoimentosusuario',
            name='tipo',
            field=models.CharField(choices=[('', ''), ('pu', 'Público'), ('pv', 'Privado')], default='', max_length=2),
        ),
    ]
